name: 'PR lint'
description: 'Lint the PR'
author: 'cleartax'
who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'src/main.js'
